// How many palindromes can you find (performance)
// not finished
// https://www.codewars.com/kata/58456ab6fc7d0f019b000123

const test1 = 'abccba'
const test2 = 'pellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturmporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturmporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturmporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturmporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturmporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturmporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequunturiureinventorealiquidvoluptatumplaceatarchitectoquoconsecteturpellatexcepturitemporeaccusantiumassumendanammaioresenimcumconsequ'
const test3 = 'abcabccbacabccbababccbaaabccbaepturitemporeaccusepturitemporeaccusantepturitemporeaccusantiumassumeiumassumeantiumassume'
const test4 = 'feetea'

console.time('test time')
console.log(howManyPalindromes(test1))
console.timeEnd('test time')

function howManyPalindromes(s) {
    let res = 0
    const sLength = s.length

    for(let i = 0; i < sLength; i++) {
        let tempS = s[i]
        let revS = s[i]

        for(let j = i+1; j < sLength; j++) {
            tempS += s[j]
            revS = s[j] + revS
            if(tempS === revS) res++
        }
    }

    return res + sLength
}